# Generated by Django 4.2 on 2023-05-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_page_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='key',
            field=models.SlugField(default='Hello21__', max_length=100, verbose_name='Key'),
        ),
    ]
